PRICE_TYPE = float
VOLUME_TYPE = float
VOLUME_TYPE_PRECISION = 15

TIME_TYPE = 'datetime64[ms]'
TIME_TYPE_UNIT = 'ms'
TIME_UNITS_IN_ONE_SECOND = 1000
TIME_UNITS_IN_ONE_DAY = 24 * 60 * 60 * 1000

CONFIG_FILE_NAME = 'config.json'
